# coding: utf-8
TRANSFER = {
    TED: {
        type: 'TED',
        origem: 'conta corrente',
        bank: 'Banco do Brasil S.A',
        agency: '1000',
        account: '000012314',
        verify_number: '53',
        cpf_cnpj: '79455038889',
        name: 'Antonio',
        identification: '123456789',
        value: '501,11',
        invalid_agency: '12',
        invalid_account: '00',
        invalid_cpf: '0000',
        invalid_name: '',
        nickname: 'Tester',
        email: 'teste@teste.com.br',
    },
    agendamento_ted: {
        type: 'TED',
        origem: 'conta corrente',
        bank: 'Banco Bradesco S.A',
        agency: '0020',
        account: '20',
        verify_number: '1',
        cpf_cnpj: '52956749404',
        name: 'Pedro',
        identification: '123456789',
        value: '501,11',
        invalid_agency: '12',
        invalid_account: '00',
        invalid_cpf: '0000',
        invalid_name: '',
    },
    DOC: {
        type: 'DOC',
        origem: 'conta corrente',
        bank: 'Banco do Brasil S.A',
        agency: '1000',
        account: '000012314',
        verify_number: '53',
        cpf_cnpj: '79455038889',
        name: 'Antonio',
        identification: '123456789',
        value: '1,15',
        invalid_agency: '12',
        invalid_account: '00',
        invalid_cpf: '0000',
        invalid_name: '',
        nickname: 'Ciclano de Souza',
        email: 'teste@teste.com.br',
    },
    agendamento_doc: {
        type: 'DOC',
        origem: 'conta corrente',
        bank: 'Banco Bradesco S.A',
        agency: '0127',
        account: '0122661',
        verify_number: '4',
        cpf_cnpj: '70726575500',
        name: 'Roberta',
        identification: '123456789',
        value: '1,11',
        invalid_agency: '12',
        invalid_account: '00',
        invalid_cpf: '0000',
        invalid_name: '',
    },
    TEF: {
        type: 'TEF',
        origem: 'conta corrente',
        bank: 'Banco Itau S/A',
        agency: '1500',
        account: '021058',
        cpf_cnpj: '06116488307',
        name: 'Horacio Gomes Dalla',
        identification: '123456789',
        value: '10,00',
        invalid_agency: '12',
        invalid_account: '00',
        invalid_cpf: '0000',
        invalid_name: '',
        nickname: 'Teste Mobile',
        email: 'teste@teste.com.br',
    },
    senha_errada_1_vez: {
        type: 'TEF',
        origem: 'conta corrente',
        bank: 'Banco Itau S/A',
        agency: '1500',
        account: '021173',
        cpf_cnpj: '21366925858',
        name: 'roberta',
        identification: '123456789',
        value: '12,50',
        invalid_agency: '12',
        invalid_account: '00',
        invalid_cpf: '0000',
        invalid_name: '',
        invalid_password: '444444',

    },
    senha_errada_2_vezes: {
        type: 'TEF',
        origem: 'conta corrente',
        bank: 'Banco Itau S/A',
        agency: '1500',
        account: '021173',
        cpf_cnpj: '21366925858',
        name: 'Roberta',
        identification: '123456789',
        value: '12,50',
        invalid_agency: '12',
        invalid_account: '00',
        invalid_cpf: '0000',
        invalid_name: '',
        invalid_password: '222222',

    },
    bloqueada_cliente: {
        type: 'TEF',
        origem: 'conta corrente',
        bank: 'Banco Itau S/A',
        agency: '1500',
        account: '021173',
        cpf_cnpj: '21366925858',
        name: 'roberta',
        identification: '123456789',
        value: '12,50',
        invalid_agency: '12',
        invalid_account: '00',
        invalid_cpf: '0000',
        invalid_name: '',
        invalid_password: '333333',

    },
    saldo_conta_insuficiente: {
        type: 'TED',
        origem: 'conta corrente',
        bank: 'Banco Bradesco S.A',
        agency: '1234',
        account: '1234567',
        verify_number: '8',
        cpf_cnpj: '22470268850',
        name: 'Beltrano',
        identification: '123456789',
        value: '150000,00',
        invalid_agency: '12',
        invalid_account: '00',
        invalid_cpf: '0000',
        invalid_name: '',
    },
    limite_diário_ultrapassado: {
        type: 'TED',
        origem: 'conta corrente',
        bank: 'Banco Bradesco S.A',
        agency: '1234',
        account: '1234567',
        verify_number: '8',
        cpf_cnpj: '22470268850',
        name: 'Beltrano',
        identification: '123456789',
        value: '5000,00',
        invalid_agency: '12',
        invalid_account: '00',
        invalid_cpf: '0000',
        invalid_name: '',
    },
    limite_semanal_ultrapassado: {
        type: 'TED',
        origem: 'conta corrente',
        bank: 'Banco Bradesco S.A',
        agency: '1234',
        account: '1234567',
        verify_number: '8',
        cpf_cnpj: '22470268850',
        name: 'Beltrano',
        identification: '123456789',
        value: '2500,00',
        invalid_agency: '12',
        invalid_account: '00',
        invalid_cpf: '0000',
        invalid_name: '',
    },
    valor_acima_do_lis_cep: {
        type: 'TED',
        origem: 'conta corrente',
        bank: 'Scfi Agiplan',
        agency: '1234',
        account: '1234567',
        verify_number: '8',
        cpf_cnpj: '22470268850',
        name: 'Beltrano',
        identification: '123456789',
        value: '100000,00',
        invalid_agency: '12',
        invalid_account: '00',
        invalid_cpf: '0000',
        invalid_name: '',
    },
    valor_acima_do_lis_adicional: {
        type: 'TED',
        origem: 'conta corrente',
        bank: 'Scfi Agiplan',
        agency: '1234',
        account: '1234567',
        verify_number: '8',
        cpf_cnpj: '22470268850',
        name: 'Beltrano',
        identification: '123456789',
        value: '100000,00',
        invalid_agency: '12',
        invalid_account: '00',
        invalid_cpf: '0000',
        invalid_name: '',
    },
    não_possui_lis_contratado: {
        type: 'TED',
        origem: 'conta corrente',
        bank: 'Scfi Agiplan',
        agency: '1234',
        account: '1234567',
        verify_number: '8',
        cpf_cnpj: '22470268850',
        name: 'Beltrano',
        identification: '123456789',
        value: '999,00',
        invalid_agency: '12',
        invalid_account: '00',
        invalid_cpf: '0000',
        invalid_name: '',

    },
    conta_crédito_encerrada: {
        type: 'TED',
        origem: 'conta corrente',
        bank: 'Scfi Agiplan',
        agency: '1500',
        account: '0001000',
        verify_number: '8',
        cpf_cnpj: '22470268850',
        name: 'Beltrano',
        identification: '123456789',
        value: '5504,00',
        invalid_agency: '12',
        invalid_account: '00',
        invalid_cpf: '0000',
        invalid_name: '',

    },

    varejo_conta_crédito_encerrada: {
        type: 'TEF',
        origem: 'conta corrente',
        bank: 'Banco Itau S/A',
        agency: '1500',
        account: '010523',
        cpf_cnpj: '06116488307',
        name: 'Horacio Gomes Dalla',
        identification: '123456789',
        value: '100,00',
        nickname: 'Teste Mobile',
        email: 'teste@teste.com.br',
    },
    uniclass_conta_crédito_encerrada: {
        type: 'TEF',
        origem: 'conta corrente',
        bank: 'Banco Itau S/A',
        agency: '1500',
        account: '024268',
        cpf_cnpj: '06116488307',
        name: 'Horacio Gomes Dalla',
        identification: '123456789',
        value: '100,00',
        nickname: 'Teste Mobile',
        email: 'teste@teste.com.br',
    },
    private_conta_crédito_encerrada: {
        type: 'TEF',
        origem: 'conta corrente',
        bank: 'Banco Itau S/A',
        agency: '1500',
        account: '022502',
        cpf_cnpj: '06116488307',
        name: 'Horacio Gomes Dalla',
        identification: '123456789',
        value: '100,00',
        nickname: 'Teste Mobile',
        email: 'teste@teste.com.br',
    },
    personnalite_conta_crédito_encerrada: {
        type: 'TEF',
        origem: 'conta corrente',
        bank: 'Banco Itau S/A',
        agency: '3977',
        account: '062524',
        cpf_cnpj: '06116488307',
        name: 'Horacio Gomes Dalla',
        identification: '123456789',
        value: '100,00',
        nickname: 'Teste Mobile',
        email: 'teste@teste.com.br',
    },

    conta_crédito_bloqueada: {
        type: 'TED',
        origem: 'conta corrente',
        bank: 'Dtvm Oliveira Trust',
        agency: '1500',
        account: '0001100',
        verify_number: '6',
        cpf_cnpj: '22470268850',
        name: 'Beltrano',
        identification: '123456789',
        value: '1501,00',
        invalid_agency: '12',
        invalid_account: '00',
        invalid_cpf: '0000',
        invalid_name: '',

    },

    varejo_conta_crédito_bloqueada: {
        type: 'TEF',
        origem: 'conta corrente',
        bank: 'Banco Itau S/A',
        agency: '1500',
        account: '010473',
        cpf_cnpj: '06116488307',
        name: 'Horacio Gomes Dalla',
        identification: '123456789',
        value: '100,00',
        nickname: 'Teste Mobile',
        email: 'teste@teste.com.br',
    },
    uniclass_conta_crédito_bloqueada: {
        type: 'TEF',
        origem: 'conta corrente',
        bank: 'Banco Itau S/A',
        agency: '1500',
        account: '024524',
        cpf_cnpj: '06116488307',
        name: 'Horacio Gomes Dalla',
        identification: '123456789',
        value: '100,00',
        nickname: 'Teste Mobile',
        email: 'teste@teste.com.br',
    },
    private_conta_crédito_bloqueada: {
        type: 'TEF',
        origem: 'conta corrente',
        bank: 'Banco Itau S/A',
        agency: '1500',
        account: '012230',
        cpf_cnpj: '06116488307',
        name: 'Horacio Gomes Dalla',
        identification: '123456789',
        value: '100,00',
        nickname: 'Teste Mobile',
        email: 'teste@teste.com.br',
    },
    personnalite_conta_crédito_bloqueada: {
        type: 'TEF',
        origem: 'conta corrente',
        bank: 'Banco Itau S/A',
        agency: '3977',
        account: '020233',
        cpf_cnpj: '06116488307',
        name: 'Horacio Gomes Dalla',
        identification: '123456789',
        value: '100,00',
        nickname: 'Teste Mobile',
        email: 'teste@teste.com.br',
    },

    conta_crédito_inválida: {
        type: 'TEF',
        origem: 'conta corrente',
        bank: 'Banco Itau S/A',
        agency: '1500',
        account: '999999',
        verify_number: '5',
        cpf_cnpj: '22470268850',
        name: 'Beltrano',
        identification: '123456789',
        value: '1501,00',
        invalid_agency: '12',
        invalid_account: '00',
        invalid_cpf: '0000',
        invalid_name: '',
    },
    conta_crédito_igual_conta_débito: {
        type: 'TEF',
        origem: 'conta corrente',
        bank: 'Banco Itau S/A',
        agency: '1500',
        account: '012081',
        cpf_cnpj: '22470268850',
        name: 'Beltrano',
        identification: '123456789',
        value: '10,00',
        invalid_agency: '12',
        invalid_account: '00',
        invalid_cpf: '0000',
        invalid_name: '',

    },
    duplicidade: {
        type: 'TED',
        origem: 'conta corrente',
        bank: 'Banco do Brasil S.A.',
        agency: '0020',
        account: '20',
        verify_number: '1',
        cpf_cnpj: '06528132160',
        name: 'Pedro',
        identification: '123456789',
        value: '501,11',
        invalid_agency: '12',
        invalid_account: '00',
        invalid_cpf: '0000',
        invalid_name: '',

    },

    ###############


    ###################### aqui ######################


    agendamento_tef_recorrencia: {
        type: 'TEF',
        origem: 'conta corrente',
        bank: 'Banco Itau S/A',
        agency: '1500',
        account: '021173',
        cpf_cnpj: '21366925858',
        name: 'roberta',
        identification: 'wellingtonwellington',
        value: '12,50',
        invalid_agency: '12',
        invalid_account: '00',
        invalid_cpf: '0000',
        invalid_name: '',
        invalid_password: '123456',

    },
    agendamento_tef: {
        type: 'TEF',
        origem: 'conta corrente',
        bank: 'Banco Itau S/A',
        agency: '1500',
        account: '021173',
        cpf_cnpj: '21366925858',
        name: 'roberta',
        identification: 'wellingtonwellington',
        value: '12,50',
        invalid_agency: '12',
        invalid_account: '00',
        invalid_cpf: '0000',
        invalid_name: '',
        invalid_password: '123456',

    },
    contato_tef_existente: {
        type: 'TEF',
        origem: 'conta corrente',
        bank: 'Banco Itau S/A',
        agency: '1500',
        account: '010077',
        cpf_cnpj: '21366925858',
        name: 'Joao da Silva',
        identification: '123456789 Tef',
        value: '12,50',
        nickname: 'Beltrano',
        name_contact: '123456789 Moro',
        email: 'email@email.com.br',
        invalid_agency: '12',
        invalid_account: '00',
        invalid_cpf: '0000',
        invalid_name: '',
        invalid_password: '123456',

    },
    cadastro_tef: {
        type: 'TEF',
        origem: 'conta corrente',
        bank: 'Banco Itau S/A',
        agency: '1500',
        account: '052020',
        cpf_cnpj: '21391321812',
        name: 'roberta',
        identification: 'wellingtonwellington',
        value: '12,50',
        nickname: 'Moro',
        name_contact: '123456789 Moro',
        email: 'email@email.com.br',
        invalid_agency: '12',
        invalid_account: '00',
        invalid_cpf: '0000',
        invalid_name: '',
        invalid_password: '123456',

    },
    cadastro_doc_ted: {
        type: 'TEF',
        origem: 'conta corrente',
        bank: 'BANCO SANTANDER (BRASIL) S.A.',
        agency: '0003',
        account: '000333',
        cpf_cnpj: '51150128550',
        name: 'roberta',
        identification: 'wellingtonwellington',
        value: '12,50',
        nickname: 'Moro',
        name_contact: '123456789 1 Moro',
        email: 'email@email.com.br',
        invalid_agency: '12',
        invalid_account: '00',
        invalid_cpf: '0000',
        invalid_name: '',
        invalid_password: '123456',

    },
    doc_ted_existente: {
        type: 'DOC',
        origem: 'conta corrente',
        bank: 'Banco Santander (brasil) S.A',
        agency: '3333',
        account: '034234234',
        verify_number: '3',
        cpf_cnpj: '51150128550',
        name: 'Kiko Chaves',
        identification: '123456789',
        value: '12,50',
        nickname: 'Kiko',
        email: 'email@email.com.br',
        name_contact: 'Jabson Mito',
        invalid_agency: '12',
        invalid_account: '00',
        invalid_cpf: '0000',
        invalid_name: '',
        invalid_password: '123456',

    },
    conta_itau_invalida: {
        type: 'TEF',
        origem: 'conta corrente',
        bank: 'Banco Itau S/A',
        agency: '0009',
        account: '999999',
        cpf_cnpj: '21391321812',
        name: 'roberta',
        identification: 'wellingtonwellington',
        value: '12,50',
        nickname: 'Itau Invalida',
        name_contact: '123456789 Moro',
        email: 'itau@invalida.com.br',

    },
    novo_contato_tef: {
        type: 'TEF',
        origem: 'conta corrente',
        bank: 'Banco Itau S/A',
        agency: '1500',
        account: '021173',
        cpf_cnpj: '06116488307',
        name: 'Ronaldo Fenomeno',
        identification: '123456789',
        value: '10,00',
        invalid_agency: '12',
        invalid_account: '00',
        invalid_cpf: '0000',
        invalid_name: '',
        nickname: 'Fenomeno',
        email: 'teste@teste.com.br',
    },

    novo_contato_doc_ted: {
        type: 'TED',
        origem: 'conta corrente',
        bank: 'Banco do Brasil S.A',
        agency: '1000',
        account: '000012314',
        verify_number: '53',
        cpf_cnpj: '79455038889',
        name: 'Adriano Imperador',
        identification: '123456789',
        value: '501,11',
        invalid_agency: '12',
        invalid_account: '00',
        invalid_cpf: '0000',
        invalid_name: '',
        nickname: 'Imperador',
        email: 'teste@teste.com.br',
    },
    campos_vazios: {
        type: 'TEF',
        origem: 'conta corrente',
        bank: 'Banco Itau S/A',
        agency: '1500',
        account: '999999',
        verify_number: '5',
        cpf_cnpj: '22470268850',
        name: 'Beltrano',
        identification: '123456789',
        value: '1501,00',
        invalid_agency: '',
        invalid_account: '',
        invalid_cpf: '0000',
        invalid_name: '',
    },
}
