# coding: utf-8
# Precisa revisar as traduções.
MENU_ITEMS = {
  home: 'início',
  account_balance: 'conta corrente',
  transfer: 'transferências',
  recharge: 'recarga',
  credit: 'crédito',
  voucher: 'comprovantes',
  attendance: 'atendimento',
  help_and_feedback: 'ajuda e feedback',
  exit: 'sair',
  payments: 'pagamentos',
  payments_with_bar_code: 'código de barras',
  payments_credit_card_bill: 'fatura de cartão',
  payments_dda: 'DDA',
  pyaments_to_authorize: 'débitos a autorizar',
  credit_cards: 'cartões',
  credit_cards_bill: 'faturas',
  credit_cards_limit: 'limites',
  credit_cards_bill_payment: 'pagamento de fatura',
  credit_cards_bill_installment: 'parcelamento de fatura',
  credit_cards_trip_notification: 'aviso viagem',
  credit_cards_trip_solutions: 'soluções para viagem',
  credit_cards_eletronic_bill: 'fatura digital',
  credit_cards_release: 'desbloqueio de cartões',
  credit_cards_update_password: 'troca de senha',
  investiments: 'investimentos',
  investiments_my_investiments: 'meus investimentos',
  investiments_application: 'aplicação',
  investiments_rescue: 'resgate',
  investiments_stock: 'ações',
  investiments_catalogo_de_fundos: 'catálogo de fundos',
  savings: 'poupança',
  savings_balance: 'extrato',
  savings_application: 'aplicação',
  savings_rescue: 'resgate',
  trip: 'viagem',
  trip_services: 'serviços para viagem',
  trip_itau_travel_money: 'Itaú Travel Money',
  trip_notification: 'aviso viagem',
  trip_insurance: 'seguro viagem',
  trip_global_travel_card: 'Global Travel Card',
  security: 'segurança',
  security_itoken_app: 'iToken no aplicativo',
  security_itoken_sms: 'iToken no SMS',
  security_computer_app: 'aplicativo no computador'
}
